// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./commonComponents/Header.vue')['default']
    ImportAndExport: typeof import('./commonComponents/ImportAndExport.vue')['default']
    KeyIn: typeof import('./commonComponents/KeyIn.vue')['default']
    LookOver: typeof import('./commonComponents/LookOver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./commonComponents/Search.vue')['default']
    SelectLanguage: typeof import('./commonComponents/SelectLanguage.vue')['default']
    Shown: typeof import('./commonComponents/Shown.vue')['default']
    Tabs: typeof import('./commonComponents/Tabs.vue')['default']
  }
}
